// Runs asor (or a CLI generated by `asor wrap`) the safe way from a bot:
//   - no shell, so user text can never become shell syntax
//   - the user's message goes on stdin, never on the command line
//   - `--` ends option parsing, so an agent name like "--agent-auth" cannot inject flags
//   - the bot's own secrets (Slack, Teams, ...) are removed from the child's environment
// It returns the JSON envelope: {ok, agent, contextId, taskId, state, text, artifacts, error}.
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

/** The asor CLI in this repo. Set ASOR_CLI to point at an installed copy (e.g. node_modules/asor-cli/dist/src/cli.js). */
const DEFAULT_CLI = process.env.ASOR_CLI ?? fileURLToPath(new URL('../../dist/src/cli.js', import.meta.url));

const BOT_SECRETS = /^(SLACK_|MICROSOFT_?APP|MicrosoftApp|BOT_|TEAMS_)/i;

function childEnv() {
  return Object.fromEntries(Object.entries(process.env).filter(([key]) => !BOT_SECRETS.test(key)));
}

/**
 * @param {object} opts
 * @param {string} [opts.agent]      Agent id, name, or slug (for the generic asor CLI)
 * @param {string} [opts.wrappedBin] Path to a CLI generated by `asor wrap` (then `agent` is ignored)
 * @param {string} opts.message
 * @param {string} [opts.contextId]
 * @param {string} [opts.taskId]
 * @param {string} [opts.skill]
 * @param {number} [opts.timeoutSec]
 * @returns {Promise<{ok: boolean, text: string, state: string|null, contextId: string|null, taskId: string|null, error: null|{kind: string, message: string, hint: string|null}}>}
 */
export function askAgent({ agent, wrappedBin, message, contextId, taskId, skill, timeoutSec = 120 }) {
  const flags = ['--json', '--timeout', String(timeoutSec)];
  if (contextId) flags.push('--context-id', contextId);
  if (taskId) flags.push('--task-id', taskId);
  if (skill) flags.push('--skill', skill);

  let args;
  if (wrappedBin) args = [wrappedBin, 'ask', ...flags];
  else if (agent) args = [DEFAULT_CLI, 'invoke', ...flags, '--', agent];
  else throw new Error('askAgent needs either `agent` or `wrappedBin`.');

  return runJson(args, message, (timeoutSec + 15) * 1000);
}

/** Lists agents via `asor agents list --json`. */
export function listAgents() {
  return runJson([DEFAULT_CLI, 'agents', 'list', '--json'], '', 60_000);
}

function runJson(args, input, killAfterMs) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, args, { env: childEnv(), stdio: ['pipe', 'pipe', 'pipe'], windowsHide: true });
    let stdout = '';
    let stderr = '';
    const timer = setTimeout(() => child.kill(), killAfterMs);
    child.stdout.on('data', (d) => (stdout += d));
    child.stderr.on('data', (d) => (stderr += d));
    child.on('error', (err) => resolve(failure('internal', `Could not start asor: ${err.message}`)));
    child.on('close', () => {
      clearTimeout(timer);
      // With --json the envelope is the last line on stdout (earlier lines only appear with --stream).
      const last = stdout.trim().split('\n').pop() ?? '';
      try {
        resolve(JSON.parse(stdout.trim().startsWith('[') ? stdout : last));
      } catch {
        resolve(failure('internal', stderr.trim() || 'asor produced no JSON output.'));
      }
    });
    child.stdin.end(input);
  });
}

function failure(kind, message) {
  return { ok: false, text: '', state: null, contextId: null, taskId: null, error: { kind, message, hint: null } };
}
