import { chmodSync, copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CliError } from './errors.js';
import { slugify } from './resolve.js';
import { refText, tagText, type AgentCard } from './types.js';
import { VERSION } from './version.js';
import type { PinnedAgent } from './wrapped.js';

export interface WrapOptions {
  outDir: string;
  /** Command name for the generated CLI. Defaults to the agent name as a slug. */
  command?: string;
  /** Saved asor profile the generated CLI should default to. */
  profile?: string;
  force?: boolean;
}

export interface WrapResult {
  command: string;
  outDir: string;
  binPath: string;
  files: string[];
}

/** The compiled runtime (this directory). It has no dependencies, so it is copied as-is into the generated package. */
const RUNTIME_DIR = dirname(fileURLToPath(import.meta.url));

export function commandName(card: AgentCard, override?: string): string {
  const name = slugify(override ?? card.name ?? '') || 'asor-agent';
  if (!/^[a-z0-9][a-z0-9-]*$/.test(name)) throw new CliError('usage', `"${name}" is not a valid command name.`, { hint: 'Use lowercase letters, digits, and dashes.' });
  return name;
}

export function generateWrapper(card: AgentCard, opts: WrapOptions): WrapResult {
  const command = commandName(card, opts.command);
  const outDir = resolve(opts.outDir);
  if (existsSync(outDir) && readdirSync(outDir).length > 0 && !opts.force) {
    throw new CliError('usage', `${outDir} already exists and is not empty.`, { hint: 'Pick another --out directory, or pass --force to overwrite.' });
  }

  const pinned: PinnedAgent = {
    id: card.id ?? null,
    name: card.name ?? command,
    command,
    description: card.description ?? '',
    skills: (card.skills ?? []).map((s) => ({
      ...(s.id ? { id: s.id } : {}),
      ...(s.name ? { name: s.name } : {}),
      ...(s.description ? { description: s.description } : {}),
      ...(s.examples?.length ? { examples: s.examples } : {}),
    })),
    ...(opts.profile ? { profile: opts.profile } : {}),
  };

  const files: string[] = [];
  const write = (rel: string, contents: string, mode?: number) => {
    const path = join(outDir, rel);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, contents.endsWith('\n') ? contents : `${contents}\n`);
    if (mode !== undefined) {
      try {
        chmodSync(path, mode);
      } catch {
        // Not meaningful on Windows.
      }
    }
    files.push(rel.replace(/\\/g, '/'));
  };

  for (const rel of runtimeFiles(RUNTIME_DIR)) {
    const dest = join(outDir, 'lib', rel);
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(join(RUNTIME_DIR, rel), dest);
    files.push(`lib/${rel.replace(/\\/g, '/')}`);
  }

  const binRel = `bin/${command}.js`;
  write(
    binRel,
    `#!/usr/bin/env node
// Generated by asor-cli ${VERSION} (\`asor wrap\`). Regenerate instead of editing.
import { runWrapped } from '../lib/wrapped.js';

const AGENT = ${JSON.stringify(pinned, null, 2)};

process.exitCode = await runWrapped(process.argv.slice(2), AGENT);
`,
    0o755,
  );
  write('package.json', JSON.stringify(packageJson(card, command, binRel), null, 2));
  write('tool.json', JSON.stringify(toolDefinition(card, command), null, 2));
  write('SKILL.md', skillMd(card, command));
  write('README.md', readme(card, command, pinned));
  write('agent-card.json', JSON.stringify(card, null, 2));

  return { command, outDir, binPath: join(outDir, binRel), files };
}

/** Only the generator, the web UI, and the asor router stay out of generated CLIs; they need none of them. */
const NOT_VENDORED = new Set(['ui', 'cli.js', 'wrap.js', 'index.js']);

function runtimeFiles(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (dir === base && NOT_VENDORED.has(entry.name)) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...runtimeFiles(full, base));
    else if (entry.name.endsWith('.js')) out.push(relative(base, full));
  }
  return out;
}

export interface Snippet {
  surface: string;
  description: string;
  code: string;
}

/** Copy-paste recipes for using a generated CLI on each surface. Shown by `asor wrap` and the web UI. */
export function surfaceSnippets(result: WrapResult, opts: { tenant?: string; profile?: string } = {}): Snippet[] {
  const { command, outDir, binPath } = result;
  const q = (p: string) => (/\s/.test(p) ? `"${p}"` : p);
  return [
    {
      surface: 'Install',
      description: 'Put the command on your PATH. Or skip this and run the bin with node.',
      code: `npm install -g ${q(outDir)}\n# or, without installing:\nnode ${q(binPath)} --help`,
    },
    {
      surface: 'Terminal / scripts',
      description: 'Pipe the prompt in and get JSON out. The exit code tells you what happened.',
      code: `${command} ask "What can you help me with?"\necho "What can you help me with?" | ${command} ask --json | jq -r .text`,
    },
    {
      surface: 'Credentials',
      description: opts.profile
        ? `The CLI uses the saved asor profile "${opts.profile}" on this machine. Anywhere else, set these instead:`
        : 'The CLI reads the saved asor profile on this machine. On a server or bot host, set these instead:',
      code: `ASOR_TENANT=${opts.tenant ?? '<tenant alias>'}\nASOR_CLIENT_ID=<api client id>\nASOR_CLIENT_SECRET=<api client secret>\nASOR_REFRESH_TOKEN=<refresh token>\n# ASOR_HOST=us.agent.workday.com`,
    },
    {
      surface: 'Slack',
      description: 'The bundled Bolt example answers @mentions with this agent only.',
      code: `# examples/slack-bolt/.env\nASOR_WRAPPED_BIN=${binPath}`,
    },
    {
      surface: 'Microsoft Teams',
      description: 'The bundled Bot Framework example sends every message to this agent.',
      code: `# examples/teams/.env\nASOR_WRAPPED_BIN=${binPath}`,
    },
    {
      surface: 'Claude Code',
      description: 'Install the generated SKILL.md so Claude calls the agent when it is relevant.',
      code: `mkdir -p .claude/skills/${command}\ncp ${q(join(outDir, 'SKILL.md'))} .claude/skills/${command}/SKILL.md`,
    },
    {
      surface: 'Any LLM tool-calling bot',
      description: 'Register tool.json as a tool. When the model calls it, run the command with the message on stdin.',
      code: `${q(join(outDir, 'tool.json'))}\n# run: ${command} ask --json   (message on stdin)`,
    },
  ];
}

function packageJson(card: AgentCard, command: string, binRel: string) {
  return {
    name: command,
    version: card.version && /^\d+\.\d+\.\d+/.test(card.version) ? card.version : '0.1.0',
    description: `CLI for the "${card.name}" Workday ASOR agent. Generated by asor-cli.`,
    private: true,
    type: 'module',
    bin: { [command]: binRel },
    engines: { node: '>=22' },
    files: ['bin', 'lib', 'tool.json', 'SKILL.md', 'agent-card.json'],
  };
}

function skillSummary(card: AgentCard): string {
  const names = (card.skills ?? []).map((s) => s.name ?? s.id).filter(Boolean);
  return names.length ? ` Skills: ${names.join('; ')}.` : '';
}

/**
 * A function-calling tool definition. Bots that let an LLM pick tools can load this, then run the command in
 * `invocation` with the message on stdin and parse the JSON envelope from stdout.
 */
export function toolDefinition(card: AgentCard, command: string) {
  const skillIds = (card.skills ?? []).map((s) => s.id).filter((id): id is string => Boolean(id));
  return {
    name: command.replace(/-/g, '_'),
    description: `${card.description ?? `Ask the ${card.name} agent.`}${skillSummary(card)}`.trim(),
    input_schema: {
      type: 'object',
      properties: {
        message: { type: 'string', description: 'What to ask the agent, in natural language.' },
        ...(skillIds.length ? { skill: { type: 'string', enum: skillIds, description: 'Optional: the skill to target.' } } : {}),
        context_id: { type: 'string', description: 'Optional: contextId from a previous answer, to continue that conversation.' },
        task_id: { type: 'string', description: 'Optional: taskId of a task in state "input-required" that this message answers.' },
      },
      required: ['message'],
      additionalProperties: false,
    },
    invocation: {
      command,
      args: ['ask', '--json'],
      stdin: 'message',
      flags: { skill: '--skill', context_id: '--context-id', task_id: '--task-id' },
    },
    output: {
      format: 'json',
      description: 'One JSON object: {ok, agent, contextId, taskId, state, text, artifacts, error}. Show `text` to the user. Keep `contextId` for follow-ups. If state is "input-required", ask the user and reply with the same context_id and task_id.',
    },
  };
}

function skillMd(card: AgentCard, command: string): string {
  const skills = (card.skills ?? [])
    .map((s) => {
      const tags = (s.tags ?? []).map(tagText).filter(Boolean);
      const ex = (s.examples ?? []).map((e) => `  - e.g. "${e}"`).join('\n');
      return `- **${s.name ?? s.id}**${s.id ? ` (\`--skill ${s.id}\`)` : ''}${s.description ? `: ${s.description}` : ''}${tags.length ? ` _(tags: ${tags.join(', ')})_` : ''}${ex ? `\n${ex}` : ''}`;
    })
    .join('\n');
  const description = `Ask the "${card.name}" Workday agent${card.description ? `: ${card.description.replace(/\s+/g, ' ').replace(/"/g, "'")}` : '.'} Use it whenever the user needs what this agent covers.`;
  return `---
name: ${command}
description: ${JSON.stringify(description)}
---

# ${card.name}

${card.description ?? ''}

This agent is registered in a Workday tenant's Agent System of Record (ASOR). Call it through the \`${command}\` CLI.

## How to call it

Pass the user's request on **stdin** (never paste it into the command line) and always use \`--json\`:

\`\`\`bash
printf '%s' "<the user's request>" | ${command} ask --json
\`\`\`

The command prints one JSON object:

\`\`\`json
{ "ok": true, "state": "completed", "text": "…answer…", "contextId": "…", "taskId": "…", "artifacts": [], "error": null }
\`\`\`

- Show \`text\` to the user.
- **Follow-ups:** add \`--context-id <contextId>\` from the previous answer.
- **\`state: "input-required"\`:** the agent needs more from the user. Ask them, then send the answer with both \`--context-id\` and \`--task-id\`.
- **\`ok: false\`:** read \`error.message\` and \`error.hint\`. Exit code 3 means credentials. Tell the user and do not retry. Exit code 5 means the agent failed or timed out, and one retry is reasonable.

## Skills
${skills || '- (none listed)'}
`;
}

function readme(card: AgentCard, command: string, pinned: PinnedAgent): string {
  return `# ${command}

A command-line wrapper for the **${card.name}** agent registered in Workday's Agent System of Record (ASOR).
It was generated by [asor-cli](https://github.com/gilfila/asor-cli) \`${VERSION}\` and has no dependencies beyond Node.js 22+.

| | |
|---|---|
| Agent | ${card.name}${card.version ? ` v${card.version}` : ''} |
| ASOR id | ${pinned.id ?? '(none, resolved by name)'} |
| Provider | ${refText(card.provider) ?? '-'} |
| Endpoint | ${card.url ?? '-'} |

## Install

\`\`\`bash
npm install -g .
\`\`\`

You can also run it in place with \`node bin/${command}.js\`.

## Credentials

It uses the same settings as \`asor\`, which is either:
- a profile saved with \`asor login\`${pinned.profile ? ` (it defaults to the profile \`${pinned.profile}\`)` : ''}, or
- environment variables. This is the usual choice for bots:

\`\`\`bash
export ASOR_TENANT=... ASOR_CLIENT_ID=... ASOR_CLIENT_SECRET=... ASOR_REFRESH_TOKEN=...
# optional: ASOR_HOST (default us.agent.workday.com), ASOR_AGENT_AUTH=none|workday|bearer
\`\`\`

## Use

\`\`\`bash
${command} ask "What can you do?"
echo "What can you do?" | ${command} ask --json     # for bots: prompt on stdin, JSON out
${command} ask --context-id <id> "and next year?"   # continue a conversation
${command} info                                      # live agent definition
${command} skills
\`\`\`

## Plug it into a surface

- **LLM tool-calling bots** (Slack, Teams, custom): load \`tool.json\`. When the model calls the tool, run \`${command} ask --json\` with the message on stdin and return \`text\`.
- **Claude Code / agent skills:** copy \`SKILL.md\` into \`.claude/skills/${command}/SKILL.md\`.
- **Anything else:** run it like any other command. Exit code 0 means success. See \`${command} --help\`.
`;
}
