import { parseArgs } from 'node:util';
import { createContext, reportError, stdout, type Context } from './context.js';
import { CliError, ExitCode } from './errors.js';
import { a2aInvoker } from './invoke.js';
import { renderAgentCard, wrap } from './output.js';
import { resolveAgent } from './resolve.js';
import { runInvoke } from './run-invoke.js';
import type { AgentCard } from './types.js';
import { VERSION } from './version.js';

/** What `asor wrap` bakes into a generated CLI. */
export interface PinnedAgent {
  id: string | null;
  name: string;
  command: string;
  description: string;
  skills: Array<{ id?: string; name?: string; description?: string; examples?: string[] }>;
  /** Saved profile to use when neither --profile nor ASOR_PROFILE is given. */
  profile?: string;
}

const COMMANDS = new Set(['ask', 'info', 'skills', 'help']);

function skillsText(p: PinnedAgent): string {
  if (p.skills.length === 0) return '  (the agent card lists no skills)';
  return p.skills.map((s) => `  ${s.id ?? s.name}${s.name && s.id ? ` — ${s.name}` : ''}${s.description ? `\n${wrap(s.description, 76, '      ')}` : ''}`).join('\n');
}

function help(p: PinnedAgent): string {
  const skills = skillsText(p);
  return `${p.command} — ${p.name} (a Workday ASOR agent)

${wrap(p.description || 'No description.', 88)}

Usage:
  ${p.command} ask [message] [options]   Ask the agent (reads stdin when no message is given)
  ${p.command} info                      Show the agent's live definition
  ${p.command} skills                    List the agent's skills

Options for ask:
  --json                 One JSON envelope: {ok, agent, contextId, taskId, state, text, artifacts, error}
  --stream               Stream the answer as it is produced
  --skill <id>           Target one skill
  --context-id <id>      Continue a conversation (take it from the previous --json envelope)
  --task-id <id>         Answer a task that is waiting for input
  --timeout <seconds>    Default 120
  --agent-auth <mode>    none | workday | bearer
  --profile <name>       Saved asor profile to use${p.profile ? ` (default "${p.profile}")` : ''}

Skills:
${skills}

Credentials come from ASOR_* environment variables or a profile saved with \`asor login\`.
Exit codes: 0 ok · 2 usage · 3 auth/config · 4 not found/not invocable · 5 agent failed/timed out
(generated by asor-cli ${VERSION})`;
}

async function loadPinned(ctx: Context, p: PinnedAgent): Promise<AgentCard> {
  if (p.id) {
    try {
      return await ctx.client.getAgent(p.id);
    } catch (err) {
      // The agent may have been re-registered with a new id; fall back to its name.
      if (!(err instanceof CliError && err.kind === 'not_found')) throw err;
    }
  }
  return resolveAgent(ctx.client, p.name);
}

/** Entry point for a CLI generated by `asor wrap`. Returns the exit code. */
export async function runWrapped(argv: string[], pinned: PinnedAgent): Promise<number> {
  const first = argv[0];
  const command = first && COMMANDS.has(first) ? first : first === '--help' || first === '-h' ? 'help' : first === '--version' ? 'version' : 'ask';
  const args = command === 'ask' && first !== 'ask' ? argv : argv.slice(1);
  const json = argv.includes('--json');

  try {
    if (command === 'help') return stdout(help(pinned)), ExitCode.OK;
    if (command === 'version') return stdout(VERSION), ExitCode.OK;

    let parsed;
    try {
      parsed = parseArgs({
        args,
        allowPositionals: true,
        strict: true,
        options: {
          json: { type: 'boolean' },
          stream: { type: 'boolean' },
          verbose: { type: 'boolean', short: 'v' },
          help: { type: 'boolean', short: 'h' },
          profile: { type: 'string' },
          skill: { type: 'string' },
          'context-id': { type: 'string' },
          'task-id': { type: 'string' },
          timeout: { type: 'string' },
          'agent-auth': { type: 'string' },
        },
      });
    } catch (err) {
      throw new CliError('usage', (err as Error).message, { hint: `Run \`${pinned.command} --help\`.` });
    }
    const { values, positionals } = parsed;
    if (values.help) return stdout(help(pinned)), ExitCode.OK;
    if (command === 'skills') {
      // Answered from the snapshot baked in at wrap time, so it works without credentials.
      stdout(json ? JSON.stringify(pinned.skills, null, 2) : skillsText(pinned));
      return ExitCode.OK;
    }

    const profile = values.profile ?? (process.env.ASOR_PROFILE ? undefined : pinned.profile);
    const ctx = createContext({
      ...(profile ? { profile } : {}),
      json,
      verbose: Boolean(values.verbose),
      ...(values['agent-auth'] ? { agentAuth: values['agent-auth'] } : {}),
    });

    if (command === 'info') {
      const card = await loadPinned(ctx, pinned);
      const support = a2aInvoker.supports(card);
      if (json) stdout(JSON.stringify(card, null, 2));
      else stdout(renderAgentCard(card, support.ok ? { ok: true, detail: `A2A JSON-RPC at ${support.endpoint}` } : { ok: false, detail: support.reason }));
      return ExitCode.OK;
    }

    return await runInvoke(
      ctx,
      () => loadPinned(ctx, pinned),
      positionals,
      {
        json,
        stream: Boolean(values.stream),
        ...(values.skill ? { skill: values.skill } : {}),
        ...(values['context-id'] ? { contextId: values['context-id'] } : {}),
        ...(values['task-id'] ? { taskId: values['task-id'] } : {}),
        ...(values.timeout ? { timeout: values.timeout } : {}),
      },
      `${pinned.command} ask`,
    );
  } catch (err) {
    return reportError(err, json, pinned.command);
  }
}
